/* autogenerated by Processing revision 1286 on 2022-10-31 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class A3_FINAL_ extends PApplet {

int age = 34;
PImage img;

 public void setup (){
  img = loadImage("a3photos.jpg");
  img.resize(750,1000);
  /* size commented out by preprocessor */;
}

 public void draw (){
 background(255); 
 
 fill(0);
 noStroke();
 
 float tiles = mouseX/10;
 float tileSize = width/tiles;
 
 translate(tileSize/2, tileSize/2);
 
 for (int x = 0; x < tiles; x++) {
   for (int y = 0; y < tiles; y++) {
     
     int c = img.get(PApplet.parseInt(x*tileSize),PApplet.parseInt(y*tileSize));
     float size = map(brightness(c),0,255,15,0);
    
     
     ellipse(x*tileSize, y*tileSize, size, size);
   }
 }
}


  public void settings() { size(750, 1000); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "A3_FINAL_" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
